version: "3.9"
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=myrandomsecret
      - POSTGRES_DB=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
  frontend:
    image: ghcr.io/niki-on-github/serien-and-movie-planer:dev
    container_name: serien-and-movie-planer
    restart: unless-stopped
    depends_on:
      - "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=myrandomsecret
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
    ports:
      - 8080:8888
  crawler:
    image: ghcr.io/niki-on-github/serien-and-movie-crawler:dev
    container_name: serien-and-movie-crawler
    restart: unless-stopped
    depends_on:
      - "postgres"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=myrandomsecret
      - POSTGRES_DB=postgres
      - POSTGRES_HOST=postgres
